name: Build go-subtitle
on:
  pull_request:
    paths:
    - 'cli/**'
    - 'pkg/**'

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    container: golang:1.13-stretch

    steps:

    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: setup environment
      run: |
        echo "::set-env name=GOPATH::/__w/go-subtitle"
        echo "::add-path::/__w/go-subtitle/bin"
      shell: bash

    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}

    - name: build
      run: |
        cd $GITHUB_WORKSPACE
        go get -u github.com/golang/dep/cmd/dep
        dep ensure -v
        CGO_ENABLED=0 go build -o ./bin/go-subtitle .
